# Generated by Django 2.0.1 on 2018-01-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180112_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='color',
            field=models.CharField(choices=[('Yellow', 'yellow'), ('Red', 'red'), ('Blue', 'blue'), ('Green', 'green'), ('Pink', 'pink'), ('Gray', 'gray'), ('Black', 'black'), ('Orange', 'orange')], default='red', max_length=16),
        ),
    ]
