# Generated by Django 2.0.1 on 2018-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180115_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
