# Generated by Django 2.0.1 on 2018-01-12 05:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('rating', models.CharField(choices=[('Safe For Work', 'SFW'), ('Not Safe For Work', 'NSFW')], max_length=4)),
                ('editors', models.ManyToManyField(related_name='editable_boards', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderated_boards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.PositiveIntegerField(default=1)),
                ('occurance', models.DurationField(default=datetime.timedelta(30))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('replies', models.ManyToManyField(to='boards.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
