# Generated by Django 2.0.1 on 2018-01-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180115_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='rating',
            field=models.CharField(choices=[('SFW', 'Safe For Work'), ('NSFW', 'Not Safe For Work')], max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='boards.Board'),
        ),
    ]
