# Generated by Django 2.0.1 on 2018-01-17 05:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180115_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
